language: node_js
node_js:
- '0.10'
services:
- redis-server
after_script:
- npm run coveralls
env:
  global:
    secure: "XpTY+mxe8tPW/9TQMmdFm70Rp04emxcFo8SDewxBPh+KqeW2e2SdDNkS3S01EEMWLYKm7aG1lJ7tmGp48WSijcu978u2bOR3jsntVMrWhDUgnV0I3UGwjq5YBZ5JsjvNXS5+UAV8jkbwuXE0c3moTaIc1DjD9iXfQim4sqNA28KG3Seja5TQRJMC3i5fjktufof/0pJxUDteDeGWbNDVVOr0vZb1spDPfyfPpJBhkqEXgt69fkss+x7AbkQYnLDOpuSaSevb2EijURrQ2XTZ0k2G6Pvwt1k9UkPR0svEUkyI4VVx6bRMjdTHAjrWGTCs2Ez+6yBR+xt/Xr4ln7p0Hj4mvl3GxCwjnLcqfH2UixLV/Y8txGo3orfKrP61jXn/7laLVMibYcE4vhDr8VuJh8Q4jksXqO5pJsrRrZQU23Jo/itjxyoA6E+A2RFGS2gLqngLLYMK3Vq+wDrEH7kp87umdt1RwMU3yI/s1nXIwf0k/bOLmpLAxUfk1zPmTt2MZ2FS/QWIiYUd1VR+6pawebTh7Br07VOre/fvOJbznE+z6V8++7h7aTcH//rZq4RmWamzbTcLqR7Ci84OfY+HLpU09k17y+ylilopEKFNvKCHjYIr8x2ebx4SvUZPSRug1fJPuYqcRR73rrTRkXJjDZQjiIX1XzboGzbbuZ7eCA4="
